Improve ci
python/python-docs-ja pull request #40
Opened 2022-10-19 11:46 UTC by rffontenelle

- **Use the new Transifex CLI  toll:** The Python implementation named transifex-client uses Transifex's APIv2, which is deprecated and will sunset in november 2022. The new tool, called Transifex CLI, is written in Golang and is APIv3-ready. So adjusting the CI and requirements.txt is required.
- **Fix condition in the merge job]:** Having the proper condition is important to have the translation
update in the latest Python version (python-newest project), and
the condition wouldn't match the current repository.

2022-10-20 09:03 UTC, m-aciek requested changes
New Transifex CLI doesn't support `TX_TOKEN` environment variable which `update.sh`/GH Action uses. [1]

We should update this line [2] to contain the Transifex API token.

```
tx --token ${TX_TOKEN} pull -l ${LANGUAGE} --use-git-timestamps --parallel
```

[1] https://github.com/transifex/cli/issues/116
[2] https://github.com/python/python-docs-ja/blob/3.10/scripts/update.sh#L42

2022-10-20 09:03 UTC, m-aciek commented on .github/workflows/update.yml
> +          mv tx /usr/local/bin/tx
As far as I'm concerned this will leave a LICENSE file coming from new tx client in the working directory.

Consider installing in `/user/local/bin` directly.
```suggestion
        run: |
          curl -o- https://raw.githubusercontent.com/transifex/cli/master/install.sh | bash
        working-directory: /usr/local/bin
```

2022-10-20 12:57 UTC, rffontenelle commented
@m-aciek Thanks for the suggestion.

2022-10-20 13:10 UTC, m-aciek commented
Possibly we also need to change format of .tx/config file for new CLI. Is it generated automatically?

2022-10-21 01:20 UTC, rffontenelle commented
@m-aciek Currently .tx/config is recreated when scripts/update.sh runs the sed command outputting to .tx/config. Still, some changes are necessary to fit the new tx client, so thanks for bringing this up.

2022-10-28 07:03 UTC, m-aciek approved these changes

2022-11-12 11:00 UTC, rffontenelle commented
The last commit disables pushing source files to Transifex (`tx push`) because translations are now updated via [rffontenelle/docspush-transifex](https://github.com/rffontenelle/docspush-transifex), as discussed in [Python's translation mailing list](https://mail.python.org/archives/list/translation@python.org/thread/D2UA35BS2SYX522VKUVWLB7HXPHOYRWQ/).

2022-12-30 08:55 UTC, merged